[package]
name = "heapz"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"
description = "Heap/Priority Queue implementations"
repository = "https://github.com/Ruddickmg/heapz"
readme = "README.md"

[dev-dependencies]
rand = "0.8.5"
